# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Kiddo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  pod 'ParseUI'
  pod 'ParseFacebookUtilsV4'
  pod 'Branch'
  pod 'UIViewController+ODStatusBar'
  pod 'Cluster'
  # Pods for Kiddo

end
